import { AppDataSource } from '../data-source';
import { User } from '../entity/User';

// This script is generated by ChatGPT, dummy data created by Joseph Ho

async function seedUsers() {
  await AppDataSource.initialize();

  const userRepo = AppDataSource.getRepository(User);

  const users = [
    { firstName: 'Jeffery', lastName: 'Ho', age: 23 },
    { firstName: 'Jasmin', lastName: 'Ho', age: 21 },
    { firstName: 'Joseph', lastName: 'Liao', age: 26 },
    { firstName: 'Tiffany', lastName: 'Liao', age: 23 },
  ];

  for (const data of users) {                   // loop through each object in the user array
    const user = userRepo.create(data);         // create a new User instance with the data
    await userRepo.save(user);                  // save the user to the database      
    console.log(`Inserted: ${user.firstName} ${user.lastName}`);    // print confirmation message
  }

  await AppDataSource.destroy();
}

seedUsers().catch((err) => {
  console.error('Seeding failed:', err);
});