name: CI Markdown Lint & Spell Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Markdown Lint
      run: |
        npm run lint-md || echo "Markdown lint failed but continuing"

    - name: Run Spell Check
      run: |
        npm run spell-check || echo "Spell check failed but continuing"